hw_project/hw_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes.urls')),
    path('users/', include('users.urls')),
]

hw_project/quotes/urls.py
from django.urls import path

from . import views

app_name = 'quotes'

urlpatterns = [
    path('', views.main, name='home'),
    path('<int:page>', views.main, name='root_paginate'),
    path('add_author/', views.add_author, name='add_author'),
    path('add_quote/', views.add_quote, name='add_quote'),
    path('author/<int:author_id>', views.author_detail, name='author_detail'),
    path('tag/<str:tag_name>', views.quotes_by_tag, name='quotes_by_tag'),
    path('scrape/', views.scrape_data, name='scrape_data'),
]

hw_project/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from . import views
from .forms import LoginForm

app_name = 'users'

urlpatterns = [
    path('signup/', views.RegisterView.as_view(), name = 'signup'),
    path('login/', LoginView.as_view(template_name='users/login.html', form_class=LoginForm, redirect_authenticated_user=True),
         name = 'login'),
    path('logout/', LogoutView.as_view(next_page='quotes:home'), name = 'logout'),
]

hw_project/quotes/models.py
from django.db import models

# Create your models here.

class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    create_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.fullname


class Tag(models.Model):
    name = models.CharField(max_length=150, null=False, unique=True)

    def __str__(self):
        return self.name


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    create_at = models.DateTimeField(auto_now_add=True)

hw_project/users/models.py
from django.db import models

# Create your models here.

hw_project/quotes/forms.py
from django import forms
from .models import Author, Quote, Tag


class AuthorForm(forms.ModelForm):

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']
        widgets = {
            'fullname': forms.TextInput(attrs={'class': 'form-control'}),
            'born_date': forms.TextInput(attrs={'class': 'form-control'}),
            'born_location': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 5}),
        }


class QuoteForm(forms.ModelForm):

    class Meta:
        model = Quote
        fields = ['quote', 'author', 'tags']
        widgets = {
            'quote': forms.Textarea(attrs={'class': 'form-control', 'rows': 5}),
            'author': forms.Select(attrs={'class': 'form-control'}),
            'tags': forms.SelectMultiple(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['author'].queryset = Author.objects.all()
        self.fields['tags'].queryset = Tag.objects.all()

hw_project/users/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import CharField, TextInput, EmailInput, EmailField, PasswordInput


class RegisterForm(UserCreationForm):
    username = CharField(max_length=16, min_length=3, required=True, widget=TextInput(attrs={"class": "form-control"}))
    email = EmailField(max_length=25, required=True, widget=EmailInput(attrs={"class": "form-control"}))
    password1 = CharField(required=True, widget=PasswordInput(attrs={"class": "form-control"}))
    password2 = CharField(required=True, widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class LoginForm(AuthenticationForm):
    username = CharField(max_length=16, min_length=3, required=True, widget=TextInput(attrs={"class": "form-control"}))
    password = CharField(required=True, widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ('username', 'password')

hw_project/quotes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.contrib import messages
from django.db.models import Count

from bson.objectid import ObjectId
from .forms import AuthorForm, QuoteForm
from .models import Author, Quote, Tag
from .utils import get_mongodb, scrape_and_save_data
# Create your views here.

@login_required
def add_author(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Author added successfully!")
            return redirect('quotes:home')
    else:
        form = AuthorForm()

    return render(request, 'quotes/add_author.html', {'form': form})


@login_required
def add_quote(request):
    if request.method == "POST":
        form = QuoteForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Quote added successfully!")
            return redirect('quotes:home')
    else:
        form = QuoteForm()

    return render(request, 'quotes/add_quote.html', {'form': form})


def author_detail(request, author_id):
    author = get_object_or_404(Author, id=author_id)
    quotes = Quote.objects.filter(author=author)
    return render(request, 'quotes/author_detail.html', {'author': author, 'quotes': quotes})


def quotes_by_tag(request, tag_name):
    quotes = Quote.objects.filter(tags__name=tag_name)
    return render(request, 'quotes/quotes_by_tag.html', {'quotes': quotes, 'tag_name': tag_name})


@login_required
def scrape_data(request):
    if request.method == "POST":
        scrape_url = request.POST.get('scrape_url')
        try:
            result = scrape_and_save_data(scrape_url)
            messages.success(request, result)
        except Exception as e:
            messages.error(request, f'Error during scraping: {e}')
        return redirect('quotes:home')

    return render(request, 'quotes/scrape.html')


def main(request, page=1):
    quotes = Quote.objects.all().order_by('-create_at')

    per_page = 10
    paginator = Paginator(quotes, per_page)
    quotes_on_page = paginator.page(page)

    top_tags = Tag.objects.annotate(num_quotes=Count('quote')).order_by('-num_quotes')[:10]

    return render(request, 'quotes/index.html', context={'quotes': quotes_on_page, 'top_tags': top_tags})

hw_project/users/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages

from .forms import RegisterForm


class RegisterView(View):
    template_name = 'users/signup.html'
    form_class =RegisterForm


    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(to="quotes:home")
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        return render(request, self.template_name, {"form": self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            messages.success(request, f"Congratulations to {username}. Your account has been successfully created.")
            return redirect(to="users:login")
        return render(request, self.template_name, {"form": form})

hw_project/quotes/templates/quotes/add_author.html
{% extends 'quotes/base.html' %}

{% block body %}
<div class="container mt-3">
    <h2>Add new author</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

         {% if form.errors %}
        <div class="alert alert-danger">
            <ul>
                {% for field, errors in form.errors.items %}
                <li>
                    {{ field|capfirst }}:
                    <ul>
                        {% for error in errors %}
                        <li>
                            {{ error }}
                        </li>
                        {% endfor %}
                    </ul>
                </li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </form>
</div>

{% endblock %}

hw_project/quotes/templates/quotes/add_quote.html
{% extends 'quotes/base.html' %}

{% block body %}
<div class="container mt-3">
    <h2>Add new quote</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        {% if form.errors %}
        <div class="alert alert-danger">
            <ul>
                {% for field, errors in form.errors.items %}
                <li>
                    {{ field|capfirst }}:
                    <ul>
                        {% for error in errors %}
                        <li>
                            {{ error }}
                        </li>
                        {% endfor %}
                    </ul>
                </li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </form>
</div>
{% endblock %}

hw_project/quotes/templates/quotes/author_detail.html
{% extends 'quotes/base.html' %}

{% block body %}
<div class="container mt-3">
    <h2>{{ author.fullname }}</h2>

    <div class="author_details mt-4">
        <p><strong>Born date</strong>{{ author.born_date }}</p>
        <p><strong>Born location</strong>{{ author.born_location }}</p>
        <p><strong>Description</strong>{{ author.description }}</p>
    </div>

    <h3 class="mt-5">Quotes</h3>
    <ul class="list-group mt-3">
        {% for quote in quotes %}
        <li class="list-group-item">{{ quote.quote }}</li>
        {% empty %}
        <li class="list-group-item text-muted">This author has no citations.</li>
        {% endfor %}
    </ul>

    <div class="mt-4">
        <a href="{% url 'quotes:home' %}" class="btn btn-primary">Return to home</a>
    </div>

</div>

{% endblock %}

hw_project/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Homework</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
</head>
<body>
<div class="container">
    <div class="row header-box pt-3 mb-3">
        <div class="col-md-8">
            <h1>
                <a href="{% url 'quotes:home' %}">Quotes to Scrape</a>
            </h1>
        </div>
        <div class="col-md-4">
            <p>
                {% if user.is_authenticated %}
                <a href="{% url 'quotes:add_author' %}" class="btn btn-primary">Add author</a>
                <a href="{% url 'quotes:add_quote' %}" class="btn btn-primary">Add quote</a>
            <form method="post" action="{% url 'users:logout' %}" style="display: inline;">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">Logout</button>
            </form>
            {% else %}
            <a href="{% url 'users:signup' %}" class="btn btn-primary">SignUp</a>
            <a href="{% url 'users:login' %}" class="btn btn-primary">Login</a>
            {% endif %}
            </p>
        </div>
    </div>

    {% if messages %}
    <div class="row">
        <div class="col-12">
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
        </div>
    </div>
    {% endif %}

    {% block body %} {% endblock %}

</div>
</body>
</html>

hw_project/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}
{% block body %}

<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">
            {{quote.quote}}
        </span>
            <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small></span>
                {% if quote.author and quote.author.id %}
                <p><a href="{% url 'quotes:author_detail' author_id=quote.author.id %}">(about)</a></p>
                {% else %}
                <p><strong>Author</strong>: Unknown</p>
                {% endif %}


            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}
                {% if tag %}
                <a class="tag" href="{% url 'quotes:quotes_by_tag' tag.name %}">{{ tag.name }}</a>
                {% endif %}
                {% endfor %}
            </div>
        </div>
        {% endfor %}
        <nav>
            <ul class="pager">
                <li class="previous">
                    <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                       href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                        <span aria-hidden="true">←</span> Previous
                    </a>
                </li>
                <li class="next">
                    <a class="{% if not quotes.has_next %} disabled {% endif %}"
                       href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                        Next <span aria-hidden="true">→</span></a>
                </li>
            </ul>
        </nav>
    </div>

    <div class="col-md-4">
        <div class="top-tags">
            <h3>Top ten tags</h3>
            <ul>
                {% for tag in top_tags %}
                <li>
                    <a href="{% url 'quotes:quotes_by_tag' tag.name %}">
                        {{ tag.name }} ({{ tag.num_quotes }})
                    </a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

{% endblock %}

hw_project/quotes/templates/quotes/quotes_by_tag.html
{% extends 'quotes/base.html' %}

{% block body %}
<div class="container mt-3">
    <h2>Quotes tagged with "{{ tag_name }}"</h2>
    <ul class="list-group mt-3">
        {% for quote in quotes %}
        <li class="list-group-item">
            <p class="mb-1">{{ quote.quote }}</p>
            <small>by
                <a href="{% url 'quotes:author_detail' author_id=quote.author.id %}">{{ quote.author.fullname }}</a>
            </small>
        </li>
        {% empty %}
        <li class="list-group-item text-muted">No quotes found for this tag.</li>
        {% endfor %}
    </ul>

    <div class="mt-4">
        <a href="{% url 'quotes:home' %}" class="btn btn-primary">Return to home</a>
    </div>

</div>

{% endblock %}

hw_project/quotes/templates/quotes/scrape.html
{% extends 'quotes/base.html' %}

{% block body %}
<h2>Scrape Data</h2>

<form method="post" action="{% url 'quotes:scrape_data' %}">
  {% csrf_token %}
  <div class="form-group">
    <label for="scrape-url">Scraping site URL:</label>
    <input type="url" id="scrape-url" name="scrape_url" class="form-control" placeholder="Enter the URL to scrape data from" required>
  </div>
  <button type="submit" class="btn btn-primary">Scrap data</button>
</form>
{% endblock %}

hw_project/users/templates/users/login.html
{% extends 'quotes/base.html' %}

{% block body %}
<div class="container mt-3">
    <h2>Login User</h2>

    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <span {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</span>
        {% endfor %}
    </div>
    {% endif %}

    {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{form.non_field_errors}}
    </div>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Username
                {{ form.username }}
            </label>
            <span>{{form.errors.username}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Password
                {{ form.password }}
            </label>
            <span>{{form.errors.password}}</span>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </form>
</div>
{% endblock %}

hw_project/users/templates/users/signup.html
{% extends 'quotes/base.html' %}

{% block body %}
<div class="container mt-3">
    <h2>Register User</h2>
    {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{form.non_field_errors}}
    </div>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Username
                {{ form.username }}
            </label>
            <span>{{form.errors.username}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Email
                {{ form.email }}
            </label>
            <span>{{form.errors.email}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Password
                {{ form.password1 }}
            </label>
            <span>{{form.errors.password1}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Repeat Password
                {{ form.password2 }}
            </label>
            <span>{{form.errors.password2}}</span>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </form>
</div>
{% endblock %}